import{a as y,i as l,S as P}from"./assets/vendor-DQvd0HNi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const o of s.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&a(o)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();const q="55171799-755350edf6c0ed064d9a514af",I=y.defaults.baseURL="https://pixabay.com/api/",b=async(r,t)=>{try{return(await y.get(I,{params:{key:`${q}`,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:`${t}`,per_page:15}})).data}catch{l.show({message:"There is an error loading data from the server.",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",icon:"bi bi-x-octagon",iconColor:"#fff"})}},u=document.querySelector(".gallery"),L=r=>{if(r==null){l.show({message:"Sorry, we cannot resolve your search request!",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",icon:"bi bi-x-octagon",iconColor:"#fff"});return}const t=r.map(({webformatURL:n,largeImageURL:a,tags:e,likes:s,views:o,comments:i,downloads:h})=>`<li class='gallery-item is-loading'>
        <a class='gallery-link' href='${a}'>
          <img class='gallery-image' src='${n}' alt='${e}'>
        </a>
        <div class='image-description-wrapper'>
          <p class='image-text-info'>Likes <span class='additional-text-info'>${s}</span></p>
          <p class='image-text-info'>Views <span class='additional-text-info'>${o}</span></p>
          <p class='image-text-info'>Comments <span class='additional-text-info'>${i}</span></p>
          <p class='image-text-info'>Downloads <span class='additional-text-info'>${h}</span></p>
        </div>
      </li>`).join("");u.insertAdjacentHTML("beforeend",t)};let w=new P(".gallery-link",{overlayOpacity:.8,captionDelay:250,captionsData:"alt"});const R=()=>{u.innerHTML=""},x=document.querySelector(".loader"),C=()=>{x.classList.remove("is-hidden")},d=()=>{x.classList.add("is-hidden")},m=()=>{u.style.display="flex"},$=()=>{u.style.display="none"},v=async(r,t=!1)=>{const n=document.querySelectorAll(".gallery-item"),a=Array.from(n).slice(-r),s=a.map(o=>o.querySelector(".gallery-image")).map(o=>new Promise((i,h)=>{if(o.complete&&o.naturalHeight!==0){i();return}o.addEventListener("load",()=>{i(o)}),o.addEventListener("error",()=>{i(o)})}));await Promise.allSettled(s).then(()=>{if(a.forEach(o=>o.classList.remove("is-loading")),d(),m(),k(),t){const i=a[0].getBoundingClientRect();window.scrollBy({top:i.height*2,behavior:"smooth"})}})},S=document.querySelector(".load-more-btn"),k=()=>{S.classList.remove("is-hidden-btn")},p=()=>{S.classList.add("is-hidden-btn")},g=document.querySelector(".form"),B=document.querySelector(".load-more-btn");let c="",f=1;const H=15;g.addEventListener("submit",r=>{if(r.preventDefault(),c=g.elements["search-text"].value.trim(),c===""){l.show({message:"Search field cannot be empty!",messageColor:"#fff",backgroundColor:"#ffa000",position:"topRight",icon:"bi bi-exclamation-triangle",iconColor:"#fff"});return}R(),C(),$(),p(),b(c,f).then(t=>{t.totalHits===0?(d(),m(),l.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",icon:"bi bi-x-octagon",iconColor:"#fff"})):(L(t.hits),w.refresh(),v(t.totalHits,!1))}).catch(()=>{d(),m(),l.show({message:"Failed to load image. Please, try again!",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",icon:"bi bi-x-octagon",iconColor:"#fff"})}).finally(()=>{g.reset()})});B.addEventListener("click",()=>{f+=1,C(),p(),b(c,f).then(r=>{const t=r.totalHits/H;if(f>t){l.error({message:"We're sorry, but you've reached the end of search results.",messageColor:"#fff",backgroundColor:"#09f",position:"topRight",icon:"bi bi-bell",iconColor:"#fff"}),p(),d(),m();return}return L(r.hits),w.refresh(),v(r.totalHits,!0)})});
//# sourceMappingURL=index.js.map
