import{a as h,i,S as P}from"./assets/vendor-DQvd0HNi.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const e of o)if(e.type==="childList")for(const r of e.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&n(r)}).observe(document,{childList:!0,subtree:!0});function a(o){const e={};return o.integrity&&(e.integrity=o.integrity),o.referrerPolicy&&(e.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?e.credentials="include":o.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function n(o){if(o.ep)return;o.ep=!0;const e=a(o);fetch(o.href,e)}})();const q="55171799-755350edf6c0ed064d9a514af",$=h.defaults.baseURL="https://pixabay.com/api/",y=async(t,s)=>{try{return(await h.get($,{params:{key:`${q}`,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:`${s}`,per_page:15}})).data}catch{i.show({message:"There is an error loading data from the server.",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",icon:"bi bi-x-octagon",iconColor:"#fff"})}},m=document.querySelector(".gallery"),b=t=>{if(t==null){i.show({message:"Sorry, we cannot resolve your search request!",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",icon:"bi bi-x-octagon",iconColor:"#fff"});return}const s=t.map(({webformatURL:a,largeImageURL:n,tags:o,likes:e,views:r,comments:p,downloads:S})=>`<li class='gallery-item is-loading'>
        <a class='gallery-link' href='${n}'>
          <img class='gallery-image' src='${a}' alt='${o}'>
        </a>
        <div class='image-description-wrapper'>
          <p class='image-text-info'>Likes <span class='additional-text-info'>${e}</span></p>
          <p class='image-text-info'>Views <span class='additional-text-info'>${r}</span></p>
          <p class='image-text-info'>Comments <span class='additional-text-info'>${p}</span></p>
          <p class='image-text-info'>Downloads <span class='additional-text-info'>${S}</span></p>
        </div>
      </li>`).join("");m.insertAdjacentHTML("beforeend",s)};let L=new P(".gallery-link",{overlayOpacity:.8,captionDelay:250,captionsData:"alt"});const R=()=>{m.innerHTML=""},w=document.querySelector(".loader"),x=()=>{w.classList.remove("is-hidden")},f=()=>{w.classList.add("is-hidden")},d=()=>{m.style.display="flex"},k=()=>{m.style.display="none"},C=async t=>{const s=document.querySelectorAll(".gallery-item"),a=Array.from(s).slice(-t),o=a.map(e=>e.querySelector(".gallery-image")).map(e=>new Promise((r,p)=>{if(e.complete&&e.naturalHeight!==0){r();return}e.addEventListener("load",()=>{r(e)}),e.addEventListener("error",()=>{r(e)})}));await Promise.allSettled(o).then(()=>{a.forEach(e=>e.classList.remove("is-loading")),f(),d(),I()})},v=document.querySelector(".load-more-btn"),I=()=>{v.classList.remove("is-hidden-btn")},g=()=>{v.classList.add("is-hidden-btn")},u=document.querySelector(".form"),O=document.querySelector(".load-more-btn");let l="",c=1;const E=15;u.addEventListener("submit",t=>{if(t.preventDefault(),l=u.elements["search-text"].value.trim(),l===""){i.show({message:"Search field cannot be empty!",messageColor:"#fff",backgroundColor:"#ffa000",position:"topRight",icon:"bi bi-exclamation-triangle",iconColor:"#fff"});return}R(),x(),k(),y(l,c).then(s=>{s.totalHits===0?(f(),d(),i.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",icon:"bi bi-x-octagon",iconColor:"#fff"})):(b(s.hits),L.refresh(),C())}).catch(()=>{f(),d(),i.show({message:"Failed to load image. Please, try again!",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",icon:"bi bi-x-octagon",iconColor:"#fff"})}).finally(()=>{u.reset()})});O.addEventListener("click",()=>{c+=1,x(),g(),y(l,c).then(t=>{const s=t.totalHits/E;if(c>s){i.error({message:"We're sorry, but you've reached the end of search results.",messageColor:"#fff",backgroundColor:"#09f",position:"topRight",icon:"bi bi-bell",iconColor:"#fff"}),g(),f(),d();return}return b(t.hits),L.refresh(),C(t.totalHits)})});
//# sourceMappingURL=index.js.map
