import{a as d,i as n,S as u}from"./assets/vendor-DQvd0HNi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const h="55171799-755350edf6c0ed064d9a514af",y=d.defaults.baseURL="https://pixabay.com/api/",b=s=>d.get(y,{params:{key:`${h}`,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(t=>t.data).catch(()=>{n.show({message:"There is an error loading data from the server.",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",icon:"bi bi-x-octagon",iconColor:"#fff"})}),l=document.querySelector(".gallery"),x=s=>{if(s==null){n.show({message:"Sorry, we cannot resolve your search request!",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",icon:"bi bi-x-octagon",iconColor:"#fff"});return}const t=s.map(({webformatURL:r,largeImageURL:a,tags:e,likes:o,views:i,comments:p,downloads:g})=>`<li class='gallery-item'>
        <a class='gallery-link' href='${a}'>
          <img class='gallery-image' src='${r}' alt='${e}'>
        </a>
        <div class='image-description-wrapper'>
          <p class='image-text-info'>Likes <span class='additional-text-info'>${o}</span></p>
          <p class='image-text-info'>Views <span class='additional-text-info'>${i}</span></p>
          <p class='image-text-info'>Comments <span class='additional-text-info'>${p}</span></p>
          <p class='image-text-info'>Downloads <span class='additional-text-info'>${g}</span></p>
        </div>
      </li>`).join("");l.insertAdjacentHTML("afterbegin",t)};let L=new u(".gallery-link",{overlayOpacity:.8,captionDelay:250,captionsData:"alt"});const C=()=>{l.innerHTML=""},m=document.querySelector(".loader"),w=()=>{l.style.display="none",m.classList.remove("is-hidden")},f=()=>{m.classList.add("is-hidden"),l.style.display="flex"},v=()=>{const s=document.querySelectorAll(".gallery-image"),t=Array.from(s).map(r=>new Promise((a,e)=>{r.addEventListener("load",()=>{a(r)}),r.addEventListener("error",()=>{a(r)})}));Promise.allSettled(t).then(()=>{f()})},c=document.querySelector(".form");c.addEventListener("submit",s=>{s.preventDefault();const t=c.elements["search-text"].value.trim();if(t===""){n.show({message:"Search field cannot be empty!",messageColor:"#fff",backgroundColor:"#ffa000",position:"topRight",icon:"bi bi-exclamation-triangle",iconColor:"#fff"});return}C(),w(),b(t).then(r=>{r.hits.length===0?(f(),n.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",icon:"bi bi-x-octagon",iconColor:"#fff"})):(x(r.hits),L.refresh(),v())}).catch(()=>{f(),n.show({message:"Failed to load image. Please, try again!",messageColor:"#fff",backgroundColor:"#ef4040",position:"topRight",icon:"bi bi-x-octagon",iconColor:"#fff"})}).finally(()=>{c.reset()})});
//# sourceMappingURL=index.js.map
